//! Input format-change handling for a long capture (YV92, plan finding OS-9).
//!
//! ## The defect this module exists for
//!
//! Putting AirPods in mid-recording is not a *device* change the capture path
//! can shrug off — it is a **format** change. AirPods report 24000 Hz in normal
//! operation against 48000 Hz for the built-in mic, and engaging the AirPods
//! *microphone* renegotiates the link to HFP/SCO, which drags the rate down
//! again. macOS announces this with a `kAudioDevicePropertyStreamFormat` /
//! `kAudioDevicePropertyNominalSampleRate` notification.
//!
//! Before this module nothing listened for it. The resample ratio was computed
//! once at stream open and never revisited; the device/config cache was keyed on
//! the device *name*, so the same-named device at a new rate re-used the stale
//! config; and the stream-error flag was read only at Arm and Disarm. A
//! five-second dictation always has an Arm coming, so the damage was invisible.
//! A three-hour meeting has no Arm at all: the remainder of the session is
//! either silence or — worse, because it sounds fine — resampled at the wrong
//! ratio, a clean, half-speed, wrongly-timestamped track discovered only at
//! stop.
//!
//! ## The shape of the fix
//!
//! Two halves, deliberately separated so the interesting one needs no hardware:
//!
//! * [`InputFormatWatch`] — a **pure** state machine, in the same spirit as
//!   `sysaudio::restore_plan`. Feed it what the OS says the current input device
//!   and format are; it answers with the exact action the capture path must
//!   take: close the current spill segment, write a `device_change` marker
//!   carrying the host time, and reopen with a NEW ratio. A ratio must never
//!   survive a format change, so the ratio is part of the answer rather than
//!   something the caller is trusted to recompute.
//! * the macOS listener half — `AudioObjectAddPropertyListener` on
//!   `kAudioHardwarePropertyDefaultInputDevice` and on the live input device's
//!   `kAudioDevicePropertyStreamFormat` / `kAudioDevicePropertyNominalSampleRate`.
//!   It does one thing when it fires: record which selector changed in an atomic
//!   and return. It never allocates, never locks and never touches the audio —
//!   the capture worker's watchdog picks the edge up and drives the state
//!   machine above. That way promptness comes from the listener and *correctness*
//!   comes from code that is testable without an audio device.
//!
//! Polling alone would also work (the watchdog re-reads the format every 60 s
//! regardless, so a machine where the listener cannot be installed still
//! recovers), but a minute of half-speed audio is a minute too many.
//!
//! ## YV103 — the OUTPUT side, in this same state machine (plan finding OS-3)
//!
//! 22-B's system-audio tap hangs off an aggregate device whose main sub-device
//! is the current default OUTPUT device. When that output device changes
//! (AirPods connect, a monitor's speakers appear), the aggregate is pointed at
//! the wrong thing and has to be rebuilt. Matrix row #14's naive prescription —
//! "listen for `kAudioHardwarePropertyDefaultOutputDevice`, tear down, rebuild"
//! — is **itself a documented infinite-loop bug**: creating and destroying an
//! aggregate device emits device-list and default-device notifications of its
//! own, so the listener re-triggers itself. Hyprnote, the closest open-source
//! comparable, shipped exactly that design and had to fix it (fastrepl/hyprnote
//! PR #1654, against macOS 15.7.2): "creating an infinite cycle that prevents
//! audio capture". Their fix is an `initialization_complete: Arc<AtomicBool>`
//! guard.
//!
//! (Cited by repo and number rather than by link on purpose: this module is on
//! the meeting path, and `tests/matrix_phase_offline.rs` fails the build if a
//! meeting-path module contains a URL — the standing proof behind the phase's
//! "records with Wi-Fi off" claim.)
//!
//! OS-9's own fix says of the two listener sets: *"this listener set is the same
//! debounce/guard state machine as OS-3, so build one, not two."* So the output
//! side lives **here**, on [`InputFormatWatch`], rather than in a second
//! listener object with its own copy of the same invariant — the mistake
//! `meeting_matrix`'s module docs record about re-declaring one threshold in two
//! places. Three additions, all pure:
//!
//! * **Output-side selectors** — `kAudioHardwarePropertyDefaultOutputDevice` and
//!   `kAudioHardwarePropertyDevices`, alongside the existing input-side three.
//! * **An in-flight guard** ([`InputFormatWatch::begin_aggregate_work`]) that
//!   discards every event generated by *our own* create/destroy calls, and makes
//!   a rebuild issued while a rebuild is already running a no-op rather than a
//!   double-destroy.
//! * **A coalescing ≥500 ms debounce** ([`AGGREGATE_REBUILD_DEBOUNCE_MS`]),
//!   because one AirPods connect fires a burst across all four output/input
//!   selectors at once. It is coalescing, not restarting: the window opens at
//!   the FIRST event of a burst and fires on the LATEST reading, so a device
//!   that keeps chattering cannot starve the rebuild forever.
//!
//! The answer is the same [`FormatChangeAction`] enum, with one new variant
//! ([`FormatChangeAction::RebuildAggregate`]) — 22-B's `syscapture` runs the
//! 7-step teardown/rebuild when it sees it, and calls
//! [`InputFormatWatch::finish_aggregate_work`] when it is done.

use std::sync::atomic::{AtomicU32, Ordering};

/// Everything downstream of the mic runs at 16 kHz mono; the watch is
/// constructed with the target rate rather than assuming it, so the ratio it
/// hands back is always derived, never hard-coded.
pub const DEFAULT_TARGET_RATE: u32 = 16_000;

/// How long the output-side watch coalesces a device-change burst before it
/// issues a rebuild (OS-3: "a coalescing debounce of ≥500 ms, because a single
/// AirPods connect emits a burst across `kAudioHardwarePropertyDefaultOutput
/// Device`, `kAudioHardwarePropertyDefaultInputDevice`,
/// `kAudioHardwarePropertyDevices` and `kAudioDevicePropertyStreamFormat`").
///
/// Declared **once**, here, and read by every caller: the lesson
/// `meeting_matrix`'s module docs record is that a threshold re-declared in two
/// places drifts in one of them.
pub const AGGREGATE_REBUILD_DEBOUNCE_MS: u64 = 500;

/// The nominal input format a capture stream is running at.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct InputFormat {
    pub sample_rate_hz: u32,
    pub channels: u16,
}

impl InputFormat {
    pub fn new(sample_rate_hz: u32, channels: u16) -> Self {
        Self {
            sample_rate_hz,
            channels,
        }
    }

    /// A format we refuse to act on: a zero rate or zero channels is CoreAudio
    /// (or cpal) telling us it does not know, and installing a ratio from it
    /// would be worse than keeping the old one.
    pub fn is_usable(&self) -> bool {
        self.sample_rate_hz > 0 && self.channels > 0
    }
}

/// Which OS notification (or the watchdog's own re-read) produced an
/// observation. Carried into the marker so a recovered journal says *why* the
/// segment ended, not merely that it did.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FormatEventSource {
    /// `kAudioHardwarePropertyDefaultInputDevice` — the user picked another mic.
    DefaultInputDevice,
    /// `kAudioDevicePropertyStreamFormat` — the live device renegotiated.
    StreamFormat,
    /// `kAudioDevicePropertyNominalSampleRate` — ditto, rate only.
    NominalSampleRate,
    /// `kAudioHardwarePropertyDefaultOutputDevice` (YV103/OS-3) — the system's
    /// output moved, so the tap's aggregate device is pointed at the wrong main
    /// sub-device.
    DefaultOutputDevice,
    /// `kAudioHardwarePropertyDevices` (YV103/OS-3) — the device list changed.
    /// This is the selector our OWN aggregate create/destroy fires, which is
    /// why it is never actioned without the guard and the uid comparison.
    DeviceList,
    /// No notification: the capture watchdog re-read the format on its own tick.
    /// This is the belt-and-braces path for a machine where the listener could
    /// not be installed.
    Watchdog,
}

impl FormatEventSource {
    /// Stable string for the journal marker and the logs.
    pub fn as_str(self) -> &'static str {
        match self {
            FormatEventSource::DefaultInputDevice => "default_input_device",
            FormatEventSource::StreamFormat => "stream_format",
            FormatEventSource::NominalSampleRate => "nominal_sample_rate",
            FormatEventSource::DefaultOutputDevice => "default_output_device",
            FormatEventSource::DeviceList => "device_list",
            FormatEventSource::Watchdog => "watchdog",
        }
    }

    /// Whether this selector belongs to the OUTPUT half of the watch. The two
    /// halves share one state machine but not one edge flag: the mic worker
    /// takes input edges, the tap session takes output edges, and neither
    /// swallows the other's wake-up.
    pub fn is_output_side(self) -> bool {
        matches!(
            self,
            FormatEventSource::DefaultOutputDevice | FormatEventSource::DeviceList
        )
    }

    /// Map a CoreAudio selector fourcc back to the source. Unknown selectors
    /// read as a watchdog-grade event: still worth acting on, just unlabelled.
    pub fn from_selector(selector: u32) -> Self {
        match selector {
            s if s == selectors::DEFAULT_INPUT_DEVICE => FormatEventSource::DefaultInputDevice,
            s if s == selectors::STREAM_FORMAT => FormatEventSource::StreamFormat,
            s if s == selectors::NOMINAL_SAMPLE_RATE => FormatEventSource::NominalSampleRate,
            s if s == selectors::DEFAULT_OUTPUT_DEVICE => FormatEventSource::DefaultOutputDevice,
            s if s == selectors::DEVICES => FormatEventSource::DeviceList,
            _ => FormatEventSource::Watchdog,
        }
    }
}

/// CoreAudio property selectors, as fourcc constants. Public because the
/// format-change test asserts against the real selector values rather than
/// against a test-only enum — the state machine has to be driven by the same
/// numbers the HAL sends.
pub mod selectors {
    const fn fourcc(code: &[u8; 4]) -> u32 {
        ((code[0] as u32) << 24)
            | ((code[1] as u32) << 16)
            | ((code[2] as u32) << 8)
            | (code[3] as u32)
    }

    /// `kAudioHardwarePropertyDefaultInputDevice`
    pub const DEFAULT_INPUT_DEVICE: u32 = fourcc(b"dIn ");
    /// `kAudioDevicePropertyStreamFormat`
    pub const STREAM_FORMAT: u32 = fourcc(b"sfmt");
    /// `kAudioDevicePropertyNominalSampleRate`
    pub const NOMINAL_SAMPLE_RATE: u32 = fourcc(b"nsrt");
    /// `kAudioHardwarePropertyDefaultOutputDevice` (YV103) — the output-side
    /// twin of [`DEFAULT_INPUT_DEVICE`], and the selector matrix row #14 names.
    pub const DEFAULT_OUTPUT_DEVICE: u32 = fourcc(b"dOut");
    /// `kAudioHardwarePropertyDevices` (YV103) — the whole device list. Our own
    /// aggregate create/destroy fires this one, which is precisely why the
    /// guard exists.
    pub const DEVICES: u32 = fourcc(b"dev#");
    /// `kAudioObjectPropertyScopeInput`
    pub const SCOPE_INPUT: u32 = fourcc(b"inpt");
    /// `kAudioObjectPropertyScopeGlobal`
    pub const SCOPE_GLOBAL: u32 = fourcc(b"glob");
}

/// One reading of "what is the input device and what format is it in", plus the
/// two anchors that make a marker useful: the mach host time of the event and
/// how many 16 kHz output samples had already been written when it happened.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct InputObservation {
    pub device_name: String,
    pub format: InputFormat,
    /// `mach_absolute_time` ticks — YV91's capture anchor. Zero when the caller
    /// has none (the marker then carries only the sample index).
    pub host_time: u64,
    /// Cumulative 16 kHz output samples written before this event.
    pub output_sample_index: u64,
    pub source: FormatEventSource,
}

/// One reading of "what is the system's default OUTPUT device, and what format
/// is it in" — the aggregate device's main sub-device, from the tap's point of
/// view (YV103/OS-3).
///
/// It carries its own `at_ms` rather than reading a clock, for the same reason
/// the input side carries `host_time`: the debounce has to be provable on a CI
/// runner with no audio hardware and no sleeping.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct OutputObservation {
    /// The output device's UID (`kAudioDevicePropertyDeviceUID`). A UID, not a
    /// name: OS-4's evidence is explicit that an AirPods sleep/wake keeps the
    /// same UID, so a UID comparison is the *conservative* test — it never
    /// invents a rebuild, and the ghost watchdog (YV104) catches what it misses.
    pub device_uid: String,
    /// The output device's nominal format. A 44.1↔48 kHz renegotiation on the
    /// same UID is one of OS-4's named all-zero triggers, so it counts as a
    /// change even when the device did not move.
    pub format: InputFormat,
    /// `mach_absolute_time` ticks at the event, for the marker.
    pub host_time: u64,
    /// Cumulative output samples written on the tap track before this event.
    pub output_sample_index: u64,
    pub source: FormatEventSource,
    /// A monotonic millisecond stamp, supplied by the caller. Only differences
    /// matter, so any monotonic origin works.
    pub at_ms: u64,
}

/// Why an aggregate rebuild was issued — carried on the action so the log line
/// and the meeting row say which of OS-3's and OS-4's triggers fired, rather
/// than "the device changed, somehow".
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RebuildReason {
    /// The default output device UID moved (matrix row #14 proper).
    DefaultOutputDeviceChanged,
    /// Same UID, new nominal format — OS-4's "sample-rate renegotiation on the
    /// output device (44.1 kHz ↔ 48 kHz) when another app changes output".
    OutputFormatRenegotiated,
}

impl RebuildReason {
    pub fn as_str(self) -> &'static str {
        match self {
            RebuildReason::DefaultOutputDeviceChanged => "default_output_device_changed",
            RebuildReason::OutputFormatRenegotiated => "output_format_renegotiated",
        }
    }
}

/// Which side of the capture a [`DeviceChangeMarker`] describes. The two sides
/// share the marker shape (and therefore the journal's marker-writing path)
/// while staying legible in the sidecar: a track-0 mic swap and a track-1
/// aggregate rebuild are different events and must not read as the same line.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MarkerKind {
    /// The input device or its format changed (YV92/OS-9).
    DeviceChange,
    /// The output device or its format changed, so the tap's aggregate device
    /// is being torn down and rebuilt (YV103/OS-3).
    AggregateRebuild,
}

impl MarkerKind {
    pub fn as_str(self) -> &'static str {
        match self {
            MarkerKind::DeviceChange => "device_change",
            MarkerKind::AggregateRebuild => "aggregate_rebuild",
        }
    }
}

/// The resample ratio a conversion runs at. Handed back by the state machine so
/// "the ratio after the event matches the NEW nominal rate" is something a test
/// can assert directly instead of inferring.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ResampleRatio {
    pub from_hz: u32,
    pub to_hz: u32,
}

impl ResampleRatio {
    /// Input samples per output sample.
    pub fn value(&self) -> f64 {
        if self.from_hz == 0 || self.to_hz == 0 {
            return 1.0;
        }
        self.from_hz as f64 / self.to_hz as f64
    }
}

/// The record written into the capture journal at a format change. This is the
/// 22-A shape of "close the current spill segment and open a new one": the
/// spill itself stays one continuous 16 kHz stream (that is what makes a
/// truncated file still a valid prefix), and the segment boundary is this
/// marker — the output sample index it carries is exactly where segment
/// `segment_index - 1` ends and segment `segment_index` begins. When YV91's
/// multi-file meeting journal lands, the same plan drives a real file rollover
/// with no change to the state machine.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DeviceChangeMarker {
    /// Which side of the capture moved (YV103). The input side keeps the
    /// `device_change` line the sidecar already carries; the output side writes
    /// `aggregate_rebuild` through the same path.
    pub kind: MarkerKind,
    /// The segment this marker OPENS. The first segment of a take is 0, so a
    /// marker always carries 1 or more, and the *n*-th change of one take
    /// carries *n* — which is what makes the sidecar's lines orderable, and why
    /// the watch that produces them lives on the stream rather than on the poll.
    pub segment_index: u32,
    pub host_time: u64,
    pub output_sample_index: u64,
    pub from_device: String,
    pub to_device: String,
    pub from: InputFormat,
    pub to: InputFormat,
    pub source: FormatEventSource,
}

impl DeviceChangeMarker {
    /// The JSON line appended to the journal's marker sidecar. Written by the
    /// capture worker (never the audio callback) — see `CaptureJournal`.
    pub fn to_json(&self) -> serde_json::Value {
        serde_json::json!({
            "kind": self.kind.as_str(),
            "version": 1,
            "segment_index": self.segment_index,
            "host_time": self.host_time,
            "output_sample_index": self.output_sample_index,
            "from_device": self.from_device,
            "to_device": self.to_device,
            "from_sample_rate": self.from.sample_rate_hz,
            "from_channels": self.from.channels,
            "to_sample_rate": self.to.sample_rate_hz,
            "to_channels": self.to.channels,
            "source": self.source.as_str(),
        })
    }
}

/// What the capture path must do about an observation.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum FormatChangeAction {
    /// Same device, same format. This is the common case *and* the debounce:
    /// one renegotiation makes the HAL fire several selectors, and every one
    /// after the first sees a state that already matches.
    Unchanged,
    /// The observation was not actionable (a zero rate or zero channels — the
    /// OS saying "I don't know"). The live ratio is kept; the next tick asks
    /// again.
    Ignored(&'static str),
    /// The format changed: close the current spill segment, write `marker`, and
    /// reopen the conversion at `ratio`.
    Reconfigure {
        marker: DeviceChangeMarker,
        ratio: ResampleRatio,
    },
    /// YV103/OS-3 — the OUTPUT device moved (or renegotiated its format) and the
    /// burst has settled, so the tap's process tap AND aggregate device must be
    /// destroyed and recreated: `AudioDeviceStop` → `AudioDeviceDestroyIOProcID`
    /// → `AudioHardwareDestroyAggregateDevice` → `AudioHardwareDestroyProcessTap`
    /// → recreate. That sequence is `syscapture`'s (YV100), asserted by its own
    /// teardown-order test; this action is the *decision* to run it, and the
    /// watch is already guarded when it hands this back, so the notifications
    /// the rebuild itself emits cannot re-trigger it.
    ///
    /// The caller **must** call [`InputFormatWatch::finish_aggregate_work`] when
    /// the rebuild finishes — success or failure — or the guard stays shut and
    /// the watch goes deaf.
    RebuildAggregate {
        marker: DeviceChangeMarker,
        reason: RebuildReason,
    },
}

impl FormatChangeAction {
    pub fn marker(&self) -> Option<&DeviceChangeMarker> {
        match self {
            FormatChangeAction::Reconfigure { marker, .. }
            | FormatChangeAction::RebuildAggregate { marker, .. } => Some(marker),
            _ => None,
        }
    }

    pub fn is_reconfigure(&self) -> bool {
        matches!(self, FormatChangeAction::Reconfigure { .. })
    }

    pub fn is_rebuild_aggregate(&self) -> bool {
        matches!(self, FormatChangeAction::RebuildAggregate { .. })
    }

    pub fn rebuild_reason(&self) -> Option<RebuildReason> {
        match self {
            FormatChangeAction::RebuildAggregate { reason, .. } => Some(*reason),
            _ => None,
        }
    }
}

/// The pure state machine. Holds what the live stream is actually running (not
/// what a cache thinks it is) and turns observations into actions.
///
/// **It has to be owned by the live stream, not by the poll.** The segment
/// counter is the only thing that orders the markers of one take, so a watch
/// rebuilt on every watchdog tick would hand every marker the same
/// `segment_index: 1` and a downstream rollover would collide on every file
/// after the first. `record::LiveStream` therefore keeps one of these for the
/// life of the stream and carries it across a reopen with
/// [`InputFormatWatch::resync`]; [`InputFormatWatch::restart_segments`] is what
/// starts a new take's numbering at zero.
///
/// YV103 adds the output half to this same object, deliberately: OS-9's fix says
/// *"this listener set is the same debounce/guard state machine as OS-3, so
/// build one, not two."* The two halves keep separate segment counters (a mic
/// swap orders track 0's segments; an aggregate rebuild orders track 1's) but
/// share the guard, the debounce constant and the action enum.
#[derive(Debug, Clone)]
pub struct InputFormatWatch {
    device_name: String,
    format: InputFormat,
    target_rate: u32,
    segment_index: u32,
    // ── YV103, the output half ──────────────────────────────────────────────
    /// The output device UID the aggregate's main sub-device is pointed at.
    /// Empty until [`InputFormatWatch::watch_output`] is called, which is what
    /// makes the output half inert for the mic-only 22-A path.
    output_device_uid: String,
    output_format: InputFormat,
    /// Segment numbering for the TAP track, independent of the mic track's.
    output_segment_index: u32,
    /// Hyprnote's `initialization_complete`, by another name: true while WE are
    /// creating or destroying a tap/aggregate, so the notifications that work
    /// emits are discarded instead of re-triggering it.
    aggregate_work_in_flight: bool,
    /// How many rebuilds this watch has issued. YV104 budgets on this; YV103
    /// only counts, so "exactly one rebuild for one burst" is assertable.
    rebuilds_issued: u32,
    pending: Option<PendingRebuild>,
}

/// A device-change burst that has started but not yet settled.
#[derive(Debug, Clone)]
struct PendingRebuild {
    /// When the FIRST event of the burst arrived. The window is measured from
    /// here and never restarted, so a device that chatters forever still gets
    /// its rebuild after 500 ms instead of starving.
    first_at_ms: u64,
    /// The most recent reading. The rebuild is issued against the settled
    /// state, not against the first event of the burst.
    latest: OutputObservation,
    /// `None` when the burst has settled back onto the device we are already
    /// pointed at — an AirPods connect/disconnect inside one window is no
    /// rebuild at all.
    reason: Option<RebuildReason>,
}

/// The `Ignored` reasons the output half hands back, as constants so a test can
/// assert on the exact string rather than on a substring that drifts.
impl InputFormatWatch {
    /// Returned while our own create/destroy calls are in flight — the OS-3
    /// guard, and the whole reason this is not an infinite loop.
    pub const GUARDED: &'static str =
        "an aggregate create/destroy is in flight — this event is our own";
    /// Returned while a device-change burst is still inside the debounce window.
    pub const COALESCING: &'static str = "coalescing a device-change burst";
    /// Returned when nothing has told the watch which output device the
    /// aggregate is pointed at, so there is nothing to compare against.
    pub const NO_OUTPUT_WATCHED: &'static str = "no output device is being watched";
}

impl InputFormatWatch {
    /// Start watching a stream that was just opened on `device_name` at
    /// `format`, feeding a `target_rate` conversion.
    ///
    /// The output half starts inert; a tap session turns it on with
    /// [`InputFormatWatch::watch_output`] once it knows which output device its
    /// aggregate is built around.
    pub fn new(device_name: impl Into<String>, format: InputFormat, target_rate: u32) -> Self {
        Self {
            device_name: device_name.into(),
            format,
            target_rate,
            segment_index: 0,
            output_device_uid: String::new(),
            output_format: InputFormat::new(0, 0),
            output_segment_index: 0,
            aggregate_work_in_flight: false,
            rebuilds_issued: 0,
            pending: None,
        }
    }

    /// The device the live stream is on.
    pub fn device_name(&self) -> &str {
        &self.device_name
    }

    /// The format the live stream is running at.
    pub fn format(&self) -> InputFormat {
        self.format
    }

    /// The conversion currently in force — the thing that must never survive a
    /// format change.
    pub fn ratio(&self) -> ResampleRatio {
        ResampleRatio {
            from_hz: self.format.sample_rate_hz,
            to_hz: self.target_rate,
        }
    }

    /// Which spill segment the capture is writing (0 until the first change).
    pub fn segment_index(&self) -> u32 {
        self.segment_index
    }

    /// The stream was reopened and the HAL handed back a device/format that may
    /// not be exactly what was observed a moment ago (a Bluetooth link settles,
    /// cpal picks a different default config). Track what actually opened —
    /// **without** touching the segment counter, because a reopen driven by a
    /// change already counted is the same segment, and a reopen after a plain
    /// stream error is not a segment boundary at all.
    pub fn resync(&mut self, device_name: impl Into<String>, format: InputFormat) {
        self.device_name = device_name.into();
        if format.is_usable() {
            self.format = format;
        }
    }

    /// A new take began on the same live stream. Segment numbering is per-take
    /// (the marker sidecar is retired with the take), so the counter restarts
    /// here rather than carrying yesterday's swaps into today's journal.
    pub fn restart_segments(&mut self) {
        self.segment_index = 0;
        self.output_segment_index = 0;
    }

    /// Fold one observation in. The ONLY mutation point: after a
    /// `Reconfigure` the watch already describes the new world, so a caller
    /// that fails to reopen must not pretend it succeeded — it re-observes on
    /// the next tick and gets `Unchanged`, with the stream's own error flag
    /// (polled by the same watchdog) as the backstop.
    pub fn observe(&mut self, obs: InputObservation) -> FormatChangeAction {
        if !obs.format.is_usable() {
            return FormatChangeAction::Ignored("the OS reported a zero rate or channel count");
        }
        if obs.device_name == self.device_name && obs.format == self.format {
            return FormatChangeAction::Unchanged;
        }
        self.segment_index += 1;
        let from_device = std::mem::replace(&mut self.device_name, obs.device_name);
        let from = std::mem::replace(&mut self.format, obs.format);
        let marker = DeviceChangeMarker {
            kind: MarkerKind::DeviceChange,
            segment_index: self.segment_index,
            host_time: obs.host_time,
            output_sample_index: obs.output_sample_index,
            from_device,
            to_device: self.device_name.clone(),
            from,
            to: self.format,
            source: obs.source,
        };
        FormatChangeAction::Reconfigure {
            marker,
            ratio: self.ratio(),
        }
    }

    // ── YV103 / OS-3: the output half ───────────────────────────────────────

    /// Point the output half at the device the tap's aggregate was built
    /// around. Until this is called the output half is inert and
    /// [`InputFormatWatch::observe_output`] answers
    /// [`InputFormatWatch::NO_OUTPUT_WATCHED`] — which is exactly what the
    /// mic-only 22-A path wants.
    pub fn watch_output(&mut self, device_uid: impl Into<String>, format: InputFormat) {
        self.output_device_uid = device_uid.into();
        self.output_format = format;
        self.pending = None;
    }

    /// The output device UID the aggregate is currently pointed at.
    pub fn output_device_uid(&self) -> &str {
        &self.output_device_uid
    }

    /// The output device's last-known nominal format.
    pub fn output_format(&self) -> InputFormat {
        self.output_format
    }

    /// Which segment of the TAP track is being written (0 until the first
    /// rebuild). Separate from [`InputFormatWatch::segment_index`] on purpose:
    /// the mic track and the tap track have independent segment histories, and
    /// one counter serving both would mis-order whichever one it lost.
    pub fn output_segment_index(&self) -> u32 {
        self.output_segment_index
    }

    /// How many rebuilds this watch has issued in this session. YV104's
    /// 3-rebuilds-per-meeting budget reads this; YV103 only counts.
    pub fn rebuilds_issued(&self) -> u32 {
        self.rebuilds_issued
    }

    /// Whether our own tap/aggregate work is in flight (the OS-3 guard).
    pub fn is_aggregate_work_in_flight(&self) -> bool {
        self.aggregate_work_in_flight
    }

    /// Whether a device-change burst is being coalesced right now.
    pub fn has_pending_rebuild(&self) -> bool {
        self.pending.is_some()
    }

    /// Take the guard before running any `AudioHardwareCreateProcessTap` /
    /// `AudioHardwareCreateAggregateDevice` / destroy sequence — including the
    /// FIRST one, at session start, which is the case Hyprnote's
    /// `initialization_complete` was named after.
    ///
    /// Returns `false` when the guard is already held, and that return value is
    /// the whole re-entrancy story: a caller that rebuilds only when this
    /// returns `true` cannot double-destroy or double-create, no matter how many
    /// times it is re-entered. [`FormatChangeAction::RebuildAggregate`] takes
    /// the guard on its way out, so the action itself is already the token.
    pub fn begin_aggregate_work(&mut self) -> bool {
        if self.aggregate_work_in_flight {
            return false;
        }
        self.aggregate_work_in_flight = true;
        true
    }

    /// Release the guard, adopting whatever the OS actually handed back.
    ///
    /// Idempotent, and it must be called on the FAILURE path too — a rebuild
    /// that errored still ends the in-flight window, and leaving the guard shut
    /// would make the watch deaf for the rest of the meeting.
    ///
    /// The honest cost of the guard, stated rather than hidden: a genuine
    /// user-initiated output switch that lands *inside* our create/destroy
    /// window is discarded with everything else. That is why this call adopts
    /// the OS's current reading rather than assuming the rebuild landed where it
    /// was aimed — if the user moved the output mid-rebuild, the adopted UID
    /// differs, and the next watchdog re-read (source
    /// [`FormatEventSource::Watchdog`]) sees it and rebuilds again.
    ///
    /// Adoption is guarded on both halves, for the same reason. An empty UID is
    /// not a device, it is a failed CoreAudio read — the natural value on the
    /// very failure path this call must be made on — and adopting it would
    /// empty [`InputFormatWatch::output_device_uid`], after which
    /// [`InputFormatWatch::observe_output`] short-circuits on
    /// [`InputFormatWatch::NO_OUTPUT_WATCHED`] before any comparison and no
    /// notification and no watchdog re-read can ever reach the rebuild path
    /// again. That is the same "deaf for the rest of the meeting" failure the
    /// guard release exists to prevent, arriving through the UID instead of the
    /// flag. So a blank reading keeps the last known-good device and lets the
    /// next re-read recover, exactly as an unusable format keeps the last
    /// known-good format.
    pub fn finish_aggregate_work(&mut self, device_uid: impl Into<String>, format: InputFormat) {
        self.aggregate_work_in_flight = false;
        let uid = device_uid.into();
        if !uid.is_empty() {
            self.output_device_uid = uid;
        }
        if format.is_usable() {
            self.output_format = format;
        }
        // Anything that arrived during the window was ours. Drop it.
        self.pending = None;
    }

    /// Fold one output-side reading in. Returns
    /// [`FormatChangeAction::RebuildAggregate`] only when a burst has both
    /// settled (≥ [`AGGREGATE_REBUILD_DEBOUNCE_MS`] since its first event) and
    /// still disagrees with the device the aggregate is pointed at.
    pub fn observe_output(&mut self, obs: OutputObservation) -> FormatChangeAction {
        if self.aggregate_work_in_flight {
            return FormatChangeAction::Ignored(Self::GUARDED);
        }
        if self.output_device_uid.is_empty() {
            return FormatChangeAction::Ignored(Self::NO_OUTPUT_WATCHED);
        }
        let at_ms = obs.at_ms;
        let reason = self.output_change_reason(&obs);
        match self.pending.as_mut() {
            // A burst is already open: every later event only refines what the
            // rebuild will be issued against — it never restarts the window and
            // never opens a second one.
            Some(pending) => {
                pending.latest = obs;
                pending.reason = reason;
            }
            None => match reason {
                None => return FormatChangeAction::Unchanged,
                Some(reason) => {
                    self.pending = Some(PendingRebuild {
                        first_at_ms: at_ms,
                        latest: obs,
                        reason: Some(reason),
                    })
                }
            },
        }
        self.settle(at_ms)
    }

    /// The watchdog's own tick, which is what actually fires a settled burst:
    /// the last event of a burst is by definition not followed by another, so
    /// something other than an event has to close the window.
    pub fn tick_output(&mut self, now_ms: u64) -> FormatChangeAction {
        if self.aggregate_work_in_flight {
            return FormatChangeAction::Ignored(Self::GUARDED);
        }
        self.settle(now_ms)
    }

    /// Is this reading a change worth rebuilding for?
    fn output_change_reason(&self, obs: &OutputObservation) -> Option<RebuildReason> {
        if obs.device_uid != self.output_device_uid {
            return Some(RebuildReason::DefaultOutputDeviceChanged);
        }
        // Same device. A format renegotiation still moves the aggregate's floor
        // (OS-4's 44.1↔48 trigger) — but only when both readings are real; a
        // zero rate is CoreAudio saying "I don't know yet", mid-Bluetooth-
        // handshake, and rebuilding on "I don't know" is how you get a loop.
        if obs.format.is_usable()
            && self.output_format.is_usable()
            && obs.format != self.output_format
        {
            return Some(RebuildReason::OutputFormatRenegotiated);
        }
        None
    }

    /// Fire the pending burst if its window has elapsed.
    fn settle(&mut self, now_ms: u64) -> FormatChangeAction {
        let Some(pending) = self.pending.as_ref() else {
            return FormatChangeAction::Unchanged;
        };
        if now_ms.saturating_sub(pending.first_at_ms) < AGGREGATE_REBUILD_DEBOUNCE_MS {
            return FormatChangeAction::Ignored(Self::COALESCING);
        }
        let pending = self.pending.take().expect("checked immediately above");
        match pending.reason {
            // The burst settled back onto the device we are already on — an
            // AirPods connect and disconnect inside one window. Nothing to do.
            None => FormatChangeAction::Unchanged,
            Some(reason) => self.issue_rebuild(pending.latest, reason),
        }
    }

    /// The only place a rebuild is issued, and the only place the guard is taken
    /// implicitly — so "every rebuild is guarded" is true by construction rather
    /// than by every caller remembering.
    fn issue_rebuild(
        &mut self,
        obs: OutputObservation,
        reason: RebuildReason,
    ) -> FormatChangeAction {
        self.output_segment_index += 1;
        self.rebuilds_issued += 1;
        self.aggregate_work_in_flight = true;
        let from_device = std::mem::replace(&mut self.output_device_uid, obs.device_uid);
        let from = self.output_format;
        if obs.format.is_usable() {
            self.output_format = obs.format;
        }
        let marker = DeviceChangeMarker {
            kind: MarkerKind::AggregateRebuild,
            segment_index: self.output_segment_index,
            host_time: obs.host_time,
            output_sample_index: obs.output_sample_index,
            from_device,
            to_device: self.output_device_uid.clone(),
            from,
            to: self.output_format,
            source: obs.source,
        };
        FormatChangeAction::RebuildAggregate { marker, reason }
    }
}

// ── The macOS listener half ─────────────────────────────────────────────────
// One job: turn a HAL notification into an edge the capture watchdog can see.
// It records the selector that fired and returns; every decision is made by the
// state machine above, on the worker thread, where it is safe to allocate, log
// and touch the disk.

/// The selector of the last property change the HAL announced, or 0 for none.
/// A plain atomic (not a channel, not a lock) because the listener callback
/// runs on a HAL thread with the same rules as an audio callback.
static LAST_EVENT: AtomicU32 = AtomicU32::new(0);

/// The same, for the OUTPUT half (YV103). Two flags, not one, because there are
/// two *consumers*: the mic capture worker takes input edges and the tap session
/// takes output edges. One shared flag would let an AirPods output notification
/// swallow the input edge that arrived alongside it in the same burst — and
/// mislabel the input marker's `source` while it was at it.
static LAST_OUTPUT_EVENT: AtomicU32 = AtomicU32::new(0);

/// Take the pending format-change edge, if any. Edge-triggered: the flag is
/// cleared by the read, so a burst of selectors during one renegotiation is
/// collapsed to a single wake-up (and the state machine collapses whatever the
/// burst reports to a single `Reconfigure`).
pub fn take_event() -> Option<FormatEventSource> {
    match LAST_EVENT.swap(0, Ordering::AcqRel) {
        0 => None,
        selector => Some(FormatEventSource::from_selector(selector)),
    }
}

/// The output-side edge (YV103). Same edge-triggered contract; the coalescing is
/// done properly by [`InputFormatWatch::observe_output`]'s debounce, this only
/// keeps the tap session from spinning once per notification.
pub fn take_output_event() -> Option<FormatEventSource> {
    match LAST_OUTPUT_EVENT.swap(0, Ordering::AcqRel) {
        0 => None,
        selector => Some(FormatEventSource::from_selector(selector)),
    }
}

/// Record an event exactly as the HAL callback does. Public for the tests that
/// drive the edge without an audio device.
///
/// RT-grade, like the callback that calls it: two integer comparisons and one
/// relaxed-ordered store, no allocation and no lock.
pub fn record_event(selector: u32) {
    if FormatEventSource::from_selector(selector).is_output_side() {
        LAST_OUTPUT_EVENT.store(selector, Ordering::Release);
    } else {
        LAST_EVENT.store(selector, Ordering::Release);
    }
}

#[cfg(target_os = "macos")]
mod imp {
    use super::selectors;
    use std::os::raw::c_void;
    use std::sync::Mutex;

    type OSStatus = i32;
    type AudioObjectID = u32;

    #[repr(C)]
    struct AudioObjectPropertyAddress {
        selector: u32,
        scope: u32,
        element: u32,
    }

    const K_AUDIO_OBJECT_SYSTEM_OBJECT: AudioObjectID = 1;
    const K_AUDIO_OBJECT_PROPERTY_ELEMENT_MAIN: u32 = 0;

    type ListenerProc = extern "C" fn(
        AudioObjectID,
        u32,
        *const AudioObjectPropertyAddress,
        *mut c_void,
    ) -> OSStatus;

    // CoreAudio is already linked transitively via cpal; declare the framework
    // link explicitly so this module never depends on that being the case.
    #[link(name = "CoreAudio", kind = "framework")]
    extern "C" {
        fn AudioObjectGetPropertyData(
            in_object_id: AudioObjectID,
            in_address: *const AudioObjectPropertyAddress,
            in_qualifier_data_size: u32,
            in_qualifier_data: *const c_void,
            io_data_size: *mut u32,
            out_data: *mut c_void,
        ) -> OSStatus;

        fn AudioObjectAddPropertyListener(
            in_object_id: AudioObjectID,
            in_address: *const AudioObjectPropertyAddress,
            in_listener: ListenerProc,
            in_client_data: *mut c_void,
        ) -> OSStatus;

        fn AudioObjectRemovePropertyListener(
            in_object_id: AudioObjectID,
            in_address: *const AudioObjectPropertyAddress,
            in_listener: ListenerProc,
            in_client_data: *mut c_void,
        ) -> OSStatus;
    }

    /// The listener body. RT-grade on purpose: read the selector, store it in a
    /// static atomic, return. No allocation, no lock, no logging — the client
    /// data pointer is deliberately null so there is no lifetime to get wrong.
    extern "C" fn on_property_changed(
        _object: AudioObjectID,
        count: u32,
        addresses: *const AudioObjectPropertyAddress,
        _client: *mut c_void,
    ) -> OSStatus {
        if count > 0 && !addresses.is_null() {
            // SAFETY: CoreAudio guarantees `addresses` points at `count`
            // initialised structs for the duration of the call.
            let selector = unsafe { (*addresses).selector };
            super::record_event(selector);
        }
        0
    }

    fn addr(selector: u32, scope: u32) -> AudioObjectPropertyAddress {
        AudioObjectPropertyAddress {
            selector,
            scope,
            element: K_AUDIO_OBJECT_PROPERTY_ELEMENT_MAIN,
        }
    }

    /// The addresses a live capture listens on: the system's default-input
    /// selection, and the device's own format/rate.
    fn watched(device: AudioObjectID) -> Vec<(AudioObjectID, AudioObjectPropertyAddress)> {
        vec![
            (
                K_AUDIO_OBJECT_SYSTEM_OBJECT,
                addr(selectors::DEFAULT_INPUT_DEVICE, selectors::SCOPE_GLOBAL),
            ),
            (
                device,
                addr(selectors::STREAM_FORMAT, selectors::SCOPE_INPUT),
            ),
            (
                device,
                addr(selectors::NOMINAL_SAMPLE_RATE, selectors::SCOPE_GLOBAL),
            ),
        ]
    }

    /// YV103 — the OUTPUT-side addresses, both on the system object: the
    /// default-output selection matrix row #14 names, and the device list our
    /// own aggregate create/destroy churns.
    fn watched_output() -> Vec<(AudioObjectID, AudioObjectPropertyAddress)> {
        vec![
            (
                K_AUDIO_OBJECT_SYSTEM_OBJECT,
                addr(selectors::DEFAULT_OUTPUT_DEVICE, selectors::SCOPE_GLOBAL),
            ),
            (
                K_AUDIO_OBJECT_SYSTEM_OBJECT,
                addr(selectors::DEVICES, selectors::SCOPE_GLOBAL),
            ),
        ]
    }

    /// The device whose listeners are installed, so arming is idempotent and
    /// disarming removes exactly what was added.
    static ARMED: Mutex<Option<AudioObjectID>> = Mutex::new(None);

    /// Whether the output-side listeners are installed. Separate from `ARMED`
    /// because the mic path (22-A) must not grow output listeners it never
    /// reads, and a meeting's tap must be able to disarm its own half without
    /// disturbing a dictation that is still running.
    static OUTPUT_ARMED: Mutex<bool> = Mutex::new(false);

    fn default_input_device() -> Option<AudioObjectID> {
        let address = addr(selectors::DEFAULT_INPUT_DEVICE, selectors::SCOPE_GLOBAL);
        let mut device: AudioObjectID = 0;
        let mut size = std::mem::size_of::<AudioObjectID>() as u32;
        let status = unsafe {
            AudioObjectGetPropertyData(
                K_AUDIO_OBJECT_SYSTEM_OBJECT,
                &address,
                0,
                std::ptr::null(),
                &mut size,
                &mut device as *mut _ as *mut c_void,
            )
        };
        (status == 0 && device != 0).then_some(device)
    }

    pub fn arm() -> bool {
        let Some(device) = default_input_device() else {
            return false;
        };
        let Ok(mut armed) = ARMED.lock() else {
            return false;
        };
        if *armed == Some(device) {
            return true;
        }
        if let Some(previous) = armed.take() {
            remove_for(previous);
        }
        let mut any = false;
        for (object, address) in watched(device) {
            let status = unsafe {
                AudioObjectAddPropertyListener(
                    object,
                    &address,
                    on_property_changed,
                    std::ptr::null_mut(),
                )
            };
            any |= status == 0;
        }
        if any {
            *armed = Some(device);
        }
        any
    }

    fn remove_for(device: AudioObjectID) {
        for (object, address) in watched(device) {
            unsafe {
                AudioObjectRemovePropertyListener(
                    object,
                    &address,
                    on_property_changed,
                    std::ptr::null_mut(),
                );
            }
        }
    }

    pub fn disarm() {
        let Ok(mut armed) = ARMED.lock() else {
            return;
        };
        if let Some(device) = armed.take() {
            remove_for(device);
        }
    }

    pub fn arm_output() -> bool {
        let Ok(mut armed) = OUTPUT_ARMED.lock() else {
            return false;
        };
        if *armed {
            return true;
        }
        let mut any = false;
        for (object, address) in watched_output() {
            let status = unsafe {
                AudioObjectAddPropertyListener(
                    object,
                    &address,
                    on_property_changed,
                    std::ptr::null_mut(),
                )
            };
            any |= status == 0;
        }
        if any {
            *armed = true;
        }
        any
    }

    pub fn disarm_output() {
        let Ok(mut armed) = OUTPUT_ARMED.lock() else {
            return;
        };
        if !*armed {
            return;
        }
        for (object, address) in watched_output() {
            unsafe {
                AudioObjectRemovePropertyListener(
                    object,
                    &address,
                    on_property_changed,
                    std::ptr::null_mut(),
                );
            }
        }
        *armed = false;
    }
}

#[cfg(not(target_os = "macos"))]
mod imp {
    pub fn arm() -> bool {
        false
    }
    pub fn disarm() {}
    pub fn arm_output() -> bool {
        false
    }
    pub fn disarm_output() {}
}

/// Install the CoreAudio property listeners for the current default input
/// device. Idempotent, cheap, and never fatal: `false` means the app falls back
/// to the watchdog's own 60 s re-read, which is slower but not wrong.
pub fn arm_listeners() -> bool {
    imp::arm()
}

/// Remove the listeners (the capture stream closed).
pub fn disarm_listeners() {
    imp::disarm();
}

/// YV103 — install the OUTPUT-side listeners (default output device + device
/// list) for a tap session. Same contract as [`arm_listeners`]: idempotent,
/// cheap, never fatal. Kept separate so the mic-only path grows nothing it does
/// not read.
pub fn arm_output_listeners() -> bool {
    imp::arm_output()
}

/// Remove the output-side listeners (the tap session ended).
pub fn disarm_output_listeners() {
    imp::disarm_output();
}

#[cfg(test)]
mod tests {
    use super::*;

    fn obs(name: &str, rate: u32, at: u64) -> InputObservation {
        InputObservation {
            device_name: name.to_string(),
            format: InputFormat::new(rate, 1),
            host_time: at,
            output_sample_index: at / 2,
            source: FormatEventSource::StreamFormat,
        }
    }

    #[test]
    fn an_unchanged_format_is_not_a_segment_boundary() {
        let mut watch = InputFormatWatch::new(
            "MacBook Pro Microphone",
            InputFormat::new(48_000, 1),
            DEFAULT_TARGET_RATE,
        );
        for _ in 0..5 {
            assert_eq!(
                watch.observe(obs("MacBook Pro Microphone", 48_000, 10)),
                FormatChangeAction::Unchanged
            );
        }
        assert_eq!(watch.segment_index(), 0);
        assert_eq!(watch.ratio().from_hz, 48_000);
    }

    #[test]
    fn a_zero_rate_never_installs_a_ratio() {
        let mut watch = InputFormatWatch::new("Mic", InputFormat::new(48_000, 1), 16_000);
        let action = watch.observe(InputObservation {
            device_name: "Mic".into(),
            format: InputFormat::new(0, 1),
            host_time: 1,
            output_sample_index: 1,
            source: FormatEventSource::NominalSampleRate,
        });
        assert!(matches!(action, FormatChangeAction::Ignored(_)));
        assert_eq!(watch.ratio().from_hz, 48_000);
        assert_eq!(watch.segment_index(), 0);
    }

    #[test]
    fn the_marker_names_both_sides_of_the_change() {
        let mut watch = InputFormatWatch::new("Built-in", InputFormat::new(48_000, 2), 16_000);
        let action = watch.observe(obs("AirPods Pro", 24_000, 900));
        let marker = action.marker().expect("a format change is a reconfigure");
        assert_eq!(marker.from_device, "Built-in");
        assert_eq!(marker.to_device, "AirPods Pro");
        assert_eq!(marker.from, InputFormat::new(48_000, 2));
        assert_eq!(marker.to, InputFormat::new(24_000, 1));
        assert_eq!(marker.host_time, 900);
        let json = marker.to_json();
        assert_eq!(json["kind"], "device_change");
        assert_eq!(json["to_sample_rate"], 24_000);
    }

    #[test]
    fn a_reopen_resync_is_not_a_new_segment() {
        // The reopen half of the swap: the watch already counted the change, so
        // being told what actually opened must not count it a second time.
        let mut watch = InputFormatWatch::new("Built-in", InputFormat::new(48_000, 1), 16_000);
        assert!(watch
            .observe(obs("AirPods Pro", 24_000, 10))
            .is_reconfigure());
        watch.resync("AirPods Pro", InputFormat::new(24_000, 1));
        assert_eq!(watch.segment_index(), 1, "a resync never bumps the counter");
        assert_eq!(
            watch.observe(obs("AirPods Pro", 24_000, 11)),
            FormatChangeAction::Unchanged,
            "and the next tick agrees with what actually opened"
        );
        // An unreadable format from the reopen leaves the tracked format alone.
        watch.resync("AirPods Pro", InputFormat::new(0, 0));
        assert_eq!(watch.format(), InputFormat::new(24_000, 1));
    }

    #[test]
    fn each_change_of_one_take_gets_the_next_segment_and_a_new_take_restarts() {
        // The whole AirPods sequence inside ONE take: 48k → 24k → 16k (HFP) →
        // 48k. Three markers, three DIFFERENT indices — a constant index cannot
        // order a sidecar.
        let mut watch = InputFormatWatch::new("Built-in", InputFormat::new(48_000, 1), 16_000);
        let mut indices = Vec::new();
        for (device, rate) in [
            ("AirPods Pro", 24_000),
            ("AirPods Pro", 16_000),
            ("Built-in", 48_000),
        ] {
            let action = watch.observe(obs(device, rate, 100));
            indices.push(
                action
                    .marker()
                    .expect("a change reconfigures")
                    .segment_index,
            );
            watch.resync(device, InputFormat::new(rate, 1));
        }
        assert_eq!(indices, vec![1, 2, 3]);

        watch.restart_segments();
        assert_eq!(watch.segment_index(), 0, "a new take starts at segment 0");
        let action = watch.observe(obs("AirPods Pro", 24_000, 200));
        assert_eq!(action.marker().unwrap().segment_index, 1);
    }

    #[test]
    fn selectors_map_back_to_their_sources() {
        assert_eq!(
            FormatEventSource::from_selector(selectors::STREAM_FORMAT),
            FormatEventSource::StreamFormat
        );
        assert_eq!(
            FormatEventSource::from_selector(selectors::DEFAULT_INPUT_DEVICE),
            FormatEventSource::DefaultInputDevice
        );
        assert_eq!(
            FormatEventSource::from_selector(selectors::NOMINAL_SAMPLE_RATE),
            FormatEventSource::NominalSampleRate
        );
        assert_eq!(
            FormatEventSource::from_selector(0),
            FormatEventSource::Watchdog
        );
    }

    // ── YV103 ───────────────────────────────────────────────────────────────

    #[test]
    fn the_output_selectors_are_the_fourccs_coreaudio_actually_sends() {
        // Spelled out rather than derived, because a wrong fourcc here is a
        // listener that installs cleanly and never fires — the quietest possible
        // failure. `kAudioHardwarePropertyDefaultOutputDevice` = 'dOut',
        // `kAudioHardwarePropertyDevices` = 'dev#'.
        assert_eq!(selectors::DEFAULT_OUTPUT_DEVICE, 0x644F_7574);
        assert_eq!(selectors::DEVICES, 0x6465_7623);
        assert_eq!(
            FormatEventSource::from_selector(selectors::DEFAULT_OUTPUT_DEVICE),
            FormatEventSource::DefaultOutputDevice
        );
        assert_eq!(
            FormatEventSource::from_selector(selectors::DEVICES),
            FormatEventSource::DeviceList
        );
        assert!(FormatEventSource::DefaultOutputDevice.is_output_side());
        assert!(FormatEventSource::DeviceList.is_output_side());
        for input_side in [
            FormatEventSource::DefaultInputDevice,
            FormatEventSource::StreamFormat,
            FormatEventSource::NominalSampleRate,
            FormatEventSource::Watchdog,
        ] {
            assert!(!input_side.is_output_side(), "{input_side:?}");
        }
    }

    #[test]
    fn the_output_edge_is_a_separate_flag_from_the_input_edge() {
        // One flag for two consumers would let an output notification swallow
        // the input edge that arrived beside it in the same AirPods burst — the
        // mic path would then sleep on a real format change for up to 60 s and
        // mislabel the marker's source when it woke.
        assert_eq!(take_event(), None);
        assert_eq!(take_output_event(), None);

        record_event(selectors::DEFAULT_OUTPUT_DEVICE);
        record_event(selectors::STREAM_FORMAT);
        assert_eq!(
            take_output_event(),
            Some(FormatEventSource::DefaultOutputDevice),
            "the output edge survived an input event landing after it"
        );
        assert_eq!(take_event(), Some(FormatEventSource::StreamFormat));
        assert_eq!(take_event(), None, "both edges are consumed by the read");
        assert_eq!(take_output_event(), None);
    }

    #[test]
    fn an_aggregate_rebuild_marker_is_a_different_sidecar_line_from_a_mic_swap() {
        let mut watch = InputFormatWatch::new("Mic", InputFormat::new(48_000, 1), 16_000);
        watch.watch_output("BuiltInSpeakerDevice", InputFormat::new(48_000, 2));
        watch.observe_output(OutputObservation {
            device_uid: "AirPodsPro-1a2b".into(),
            format: InputFormat::new(48_000, 2),
            host_time: 4_242,
            output_sample_index: 96_000,
            source: FormatEventSource::DefaultOutputDevice,
            at_ms: 0,
        });
        let action = watch.tick_output(AGGREGATE_REBUILD_DEBOUNCE_MS);
        let json = action.marker().expect("settled → rebuild").to_json();
        assert_eq!(json["kind"], "aggregate_rebuild");
        assert_eq!(json["source"], "default_output_device");
        assert_eq!(json["host_time"], 4_242);
        assert_eq!(json["from_device"], "BuiltInSpeakerDevice");
        assert_eq!(json["to_device"], "AirPodsPro-1a2b");

        // The mic side's line is byte-for-byte what YV92 shipped.
        let mic = watch.observe(obs("AirPods Pro", 24_000, 10));
        assert_eq!(mic.marker().unwrap().to_json()["kind"], "device_change");
    }
}
